<$PLAN9/src/mkhdr

TARG=mailfs

CFLAGS=$CFLAGS -I../common

OFILES=\
	box.$O\
	decode.$O\
	fs.$O\
	imap.$O\
	main.$O\
	sx.$O\
	thread.$O\
	util.$O\

HFILES=../common/common.h\
	../common/sys.h\
	a.h box.h imap.h sx.h

LIB=../common/libcommon.a


<$PLAN9/src/mkone

